// Shared state mutations used by more than one panel (drag/drop scheduling,
// completion toggles). Centralised so the month grid and day page behave
// identically. All lookups are tree-aware, so they work on subtasks too.
(function () {
  'use strict';
  var P = (window.Planner = window.Planner || {});

  function itemOf(id) {
    var f = P.model.find(P.store.getState().items, id);
    return f ? f.item : null;
  }

  // Move a top-level task to a day (drag it between month cells). Habits are
  // generated by their recurrence and can't be dragged onto days.
  function schedule(id, ymd) {
    var it = itemOf(id);
    if (!it || it.kind !== 'task') return;
    if (it.date === ymd) return; // no real change, no undo step
    it.date = ymd;
    P.store.commit();
  }

  function toggleDone(id, value) {
    var it = itemOf(id);
    if (!it || it.kind !== 'task') return;
    it.done = (value === undefined) ? !it.done : !!value;
    it.completedAt = it.done ? new Date().toISOString() : null;
    P.store.commit();
  }

  // Toggle whether one occurrence of a habit (on a given day) is done.
  function toggleOccurrence(id, dateKey) {
    var it = itemOf(id);
    if (!it || it.kind !== 'habit') return;
    var list = it.completedOccurrences || (it.completedOccurrences = []);
    var i = list.indexOf(dateKey);
    if (i === -1) list.push(dateKey); else list.splice(i, 1);
    P.store.commit();
  }

  function deleteItem(id) {
    var st = P.store.getState();
    if (!P.model.remove(st.items, id)) return;
    P.store.commit();
  }

  P.actions = {
    schedule: schedule,
    toggleDone: toggleDone,
    toggleOccurrence: toggleOccurrence,
    deleteItem: deleteItem
  };
})();
